export const GET_ERROR = "GET_ERROR";

export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN = " USER_LOGIN";

export const DOCTOR_REGISTER = "DOCTOR_REGISTER";
export const DOCTOR_LOGIN = " DOCTOR_LOGIN";

export const GET_ALL_Doctors = "GET_ALL_Doctors";
export const GET_ONE_DOCTOR = "GET_ONE_DOCTOR";
export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";

export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const CREATE_SERVICE = "CREATE_SERVICE";

export const GET_ALL_NEWS = "GET_ALL_NEWS";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const GET_ONE_ARTICLE = "GET_ONE_ARTICLE";

export const GET_ALL_CONDITIONS = "GET_ALL_CONDITIONS";
export const CREATE_CONDITION = "CREATE_CONDITION";
export const DELETE_CONDITION = "DELETE_CONDITION";
export const GET_ONE_CONDITION = "GET_ONE_CONDITION";
