export const GET_ERROR = "GET_ERROR";

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = " LOGIN_USER";
export const GET_ALL_Doctors = "GET_ALL_Doctors";
export const GET_ONE_DOCTOR = "GET_ONE_DOCTOR";
export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";

export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const CREATE_SERVICE = "CREATE_SERVICE";

export const GET_ALL_NEWS = "GET_ALL_NEWS";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const GET_ONE_ARTICLE = "GET_ONE_ARTICLE";

export const GET_ALL_CONDITIONS = "GET_ALL_CONDITIONS";
export const CREATE_CONDITION = "CREATE_CONDITION";
export const DELETE_CONDITION = "DELETE_CONDITION";
export const GET_ONE_CONDITION = "GET_ONE_CONDITION";
